#!/bin/bash
sed -i '.bak' 's/GAMEPLAY_EMOTE_LABEL_FIREWORKS	惊叹/GAMEPLAY_EMOTE_LABEL_FIREWORKS	哇哦.../g' zhCN/GAMEPLAY.txt
sed -i '.bak' 's/GAMEPLAY_EMOTE_LABEL_GREETINGS	问候/GAMEPLAY_EMOTE_LABEL_GREETINGS	祝你好运/g' zhCN/GAMEPLAY.txt
sed -i '.bak' 's/GAMEPLAY_EMOTE_LABEL_OOPS	失误/GAMEPLAY_EMOTE_LABEL_OOPS	基本操作~/g' zhCN/GAMEPLAY.txt
sed -i '.bak' 's/GAMEPLAY_EMOTE_LABEL_THANKS	感谢/GAMEPLAY_EMOTE_LABEL_THANKS	谢你全家！/g' zhCN/GAMEPLAY.txt
sed -i '.bak' 's/GAMEPLAY_EMOTE_LABEL_THREATEN	威胁/GAMEPLAY_EMOTE_LABEL_THREATEN	弄你信不？/g' zhCN/GAMEPLAY.txt
sed -i '.bak' 's/GAMEPLAY_EMOTE_LABEL_WELL_PLAYED	称赞/GAMEPLAY_EMOTE_LABEL_WELL_PLAYED	有点实力/g' zhCN/GAMEPLAY.txt
sed -i '.bak' 's/GAMEPLAY_EMOTE_LABEL_WOW	惊叹/GAMEPLAY_EMOTE_LABEL_WOW	哇哦.../g' zhCN/GAMEPLAY.txt
sed -i '.bak' 's/GAMEPLAY_EMOTE_SQUELCH	无视/GAMEPLAY_EMOTE_SQUELCH	滚!/g' zhCN/GAMEPLAY.txt
sed -i '.bak' 's/GAMEPLAY_END_OF_GAME_DEFEAT	败北/GAMEPLAY_END_OF_GAME_DEFEAT	算你牛逼/g' zhCN/GAMEPLAY.txt
sed -i '.bak' 's/GAMEPLAY_END_OF_GAME_DEFEAT_MAYBE	败北/GAMEPLAY_END_OF_GAME_DEFEAT_MAYBE	算你牛逼/g' zhCN/GAMEPLAY.txt
sed -i '.bak' 's/GAMEPLAY_END_OF_GAME_VICTORY	胜利/GAMEPLAY_END_OF_GAME_VICTORY	我也太强了吧/g' zhCN/GAMEPLAY.txt
sed -i '.bak' 's/GAMEPLAY_END_OF_GAME_VICTORY_MAYBE	胜利/GAMEPLAY_END_OF_GAME_VICTORY_MAYBE	我也太强了吧/g' zhCN/GAMEPLAY.txt
sed -i '.bak' 's/GAMEPLAY_END_TURN	结束回合/GAMEPLAY_END_TURN	◕‿◕ ✿/g' zhCN/GAMEPLAY.txt
sed -i '.bak' 's/GAMEPLAY_ENEMY_TURN	对手回合/GAMEPLAY_ENEMY_TURN	非酋的回合/g' zhCN/GAMEPLAY.txt
sed -i '.bak' 's/GAMEPLAY_MULLIGAN_REPLACE	替换/GAMEPLAY_MULLIGAN_REPLACE	要不起/g' zhCN/GAMEPLAY.txt
sed -i '.bak' 's/GAMEPLAY_MULLIGAN_STARTING_HAND	起始手牌/GAMEPLAY_MULLIGAN_STARTING_HAND	性感荷官，在线发牌/g' zhCN/GAMEPLAY.txt
sed -i '.bak' 's/GAMEPLAY_MULLIGAN_SUBTITLE	保留或替换卡牌/GAMEPLAY_MULLIGAN_SUBTITLE	叫或不叫地主/g' zhCN/GAMEPLAY.txt
sed -i '.bak' 's/GAMEPLAY_MULLIGAN_WAITING	对手还在选择/GAMEPLAY_MULLIGAN_WAITING	对手还在磨叽/g' zhCN/GAMEPLAY.txt
sed -i '.bak' 's/GAMEPLAY_YOUR_TURN	你的回合/GAMEPLAY_YOUR_TURN	到你了弟弟/g' zhCN/GAMEPLAY.txt

sed -i '.bak' 's/GAMEPLAY_EMOTE_HERO_01_CONCEDE	我选择死亡/GAMEPLAY_EMOTE_HERO_01_CONCEDE	我选择狗带/g' zhCN/GAMEPLAY_AUDIO.txt
sed -i '.bak' 's/GAMEPLAY_EMOTE_HERO_08_CONCEDE	你赢了。/GAMEPLAY_EMOTE_HERO_08_CONCEDE	艹你大爷，老子不玩了！/g' zhCN/GAMEPLAY_AUDIO.txt

sed -i '.bak' 's/GLOBAL_CONCEDE	认输/GLOBAL_CONCEDE	溜了溜了/g' zhCN/GLOBAL.txt
sed -i '.bak' 's/GLOBAL_CONFIRM	确认/GLOBAL_CONFIRM	OJBK/g' zhCN/GLOBAL.txt
sed -i '.bak' 's/GLOBAL_TAVERN_BRAWL	乱斗模式/GLOBAL_TAVERN_BRAWL	荒野乱斗/g' zhCN/GLOBAL.txt

sed -i '.bak' 's/GLUE_ADVENTURE	冒险模式/GLUE_ADVENTURE	贪玩蓝月/g' zhCN/GLUE.txt
sed -i '.bak' 's/GLUE_FORGE	竞技模式/GLUE_FORGE	欢乐斗地主/g' zhCN/GLUE.txt
sed -i '.bak' 's/GLUE_MATCHMAKER_PERFECT_OPPONENT	旗鼓相当的对手/GLUE_MATCHMAKER_PERFECT_OPPONENT	骑股香裆的对手/g' zhCN/GLUE.txt
sed -i '.bak' 's/GLUE_MY_COLLECTION	我的收藏/GLUE_MY_COLLECTION	欧皇的牌库/g' zhCN/GLUE.txt
sed -i '.bak' 's/GLUE_OPEN_PACKS	卡牌包/GLUE_OPEN_PACKS	金色\n传说/g' zhCN/GLUE.txt
sed -i '.bak' 's/GLUE_TOOLTIP_BUTTON_ADVENTURE_HEADLINE	冒险模式/GLUE_TOOLTIP_BUTTON_ADVENTURE_HEADLINE	贪玩蓝月/g' zhCN/GLUE.txt
sed -i '.bak' 's/GLUE_TOOLTIP_BUTTON_COLLECTION_DESC	浏览你的卡牌收藏或者构筑套牌/GLUE_TOOLTIP_BUTTON_COLLECTION_DESC	浏览欧皇的卡牌收藏或者构筑传说级套牌/g' zhCN/GLUE.txt
sed -i '.bak' 's/GLUE_TOOLTIP_BUTTON_COLLECTION_HEADLINE	我的收藏/GLUE_TOOLTIP_BUTTON_COLLECTION_HEADLINE	欧皇的牌库/g' zhCN/GLUE.txt
sed -i '.bak' 's/GLUE_TOOLTIP_BUTTON_FORGE_HEADLINE	竞技模式/GLUE_TOOLTIP_BUTTON_FORGE_HEADLINE	欢乐斗地主/g' zhCN/GLUE.txt
sed -i '.bak' 's/GLUE_TOOLTIP_BUTTON_PACKOPEN_DESC	打开你的卡牌包，将更多卡牌加入你的收藏/GLUE_TOOLTIP_BUTTON_PACKOPEN_DESC	打开你的卡牌包，将更多传说和史诗卡牌加入你的收藏/g' zhCN/GLUE.txt
sed -i '.bak' 's/GLUE_TOOLTIP_BUTTON_PACKOPEN_HEADLINE	打开卡牌包/GLUE_TOOLTIP_BUTTON_PACKOPEN_HEADLINE	获得金色传说卡牌/g' zhCN/GLUE.txt
sed -i '.bak' 's/GLUE_TOOLTIP_BUTTON_TAVERN_BRAWL_HEADLINE	乱斗模式/GLUE_TOOLTIP_BUTTON_TAVERN_BRAWL_HEADLINE	荒野乱斗/g' zhCN/GLUE.txt
sed -i '.bak' 's/GLUE_TOOLTIP_BUTTON_TOURNAMENT_DESC	寻找实力相当的对手展开对战。/GLUE_TOOLTIP_BUTTON_TOURNAMENT_DESC	炉石传说真\n尼玛好玩！/g' zhCN/GLUE.txt
sed -i '.bak' 's/GLUE_TOOLTIP_BUTTON_TOURNAMENT_HEADLINE	对战模式/GLUE_TOOLTIP_BUTTON_TOURNAMENT_HEADLINE	传说霸业/g' zhCN/GLUE.txt
sed -i '.bak' 's/GLUE_TOURNAMENT	对战模式/GLUE_TOURNAMENT	传说霸业/g' zhCN/GLUE.txt

rm zhCN/GAMEPLAY.txt.bak
rm zhCN/GAMEPLAY_AUDIO.txt.bak
rm zhCN/GLOBAL.txt.bak
rm zhCN/GLUE.txt.bak
